export interface HanjaChar {
  id: string;
  char: string;
  meaning: string;
  sound: string;
  level: string;
  stroke: number;
  radical: string;
}

export interface HanjaWord {
  id: string;
  hanja: string;
  reading: string;
  meaning: string;
  level: string;
  chars: string[];
}

export const LEVELS = [
  { id: "8", name: "8급", chars: 50, difficulty: 1 },
  { id: "준7", name: "준7급", chars: 50, difficulty: 1 },
  { id: "7", name: "7급", chars: 50, difficulty: 2 },
  { id: "준6", name: "준6급", chars: 75, difficulty: 2 },
  { id: "6", name: "6급", chars: 75, difficulty: 3 },
] as const;

export const hanjaData: HanjaChar[] = [
  // ===== 8급 (50자) =====
  { id: "H0001", char: "一", meaning: "한", sound: "일", level: "8", stroke: 1, radical: "一" },
  { id: "H0002", char: "二", meaning: "두", sound: "이", level: "8", stroke: 2, radical: "二" },
  { id: "H0003", char: "三", meaning: "석/세", sound: "삼", level: "8", stroke: 3, radical: "一" },
  { id: "H0004", char: "四", meaning: "넉", sound: "사", level: "8", stroke: 5, radical: "囗" },
  { id: "H0005", char: "五", meaning: "다섯", sound: "오", level: "8", stroke: 4, radical: "二" },
  { id: "H0006", char: "六", meaning: "여섯", sound: "육", level: "8", stroke: 4, radical: "八" },
  { id: "H0007", char: "七", meaning: "일곱", sound: "칠", level: "8", stroke: 2, radical: "一" },
  { id: "H0008", char: "八", meaning: "여덟", sound: "팔", level: "8", stroke: 2, radical: "八" },
  { id: "H0009", char: "九", meaning: "아홉", sound: "구", level: "8", stroke: 2, radical: "乙" },
  { id: "H0010", char: "十", meaning: "열", sound: "십", level: "8", stroke: 2, radical: "十" },
  { id: "H0011", char: "百", meaning: "일백", sound: "백", level: "8", stroke: 6, radical: "白" },
  { id: "H0012", char: "千", meaning: "일천", sound: "천", level: "8", stroke: 3, radical: "十" },
  { id: "H0013", char: "萬", meaning: "일만", sound: "만", level: "8", stroke: 13, radical: "艸" },
  { id: "H0014", char: "日", meaning: "날", sound: "일", level: "8", stroke: 4, radical: "日" },
  { id: "H0015", char: "月", meaning: "달", sound: "월", level: "8", stroke: 4, radical: "月" },
  { id: "H0016", char: "火", meaning: "불", sound: "화", level: "8", stroke: 4, radical: "火" },
  { id: "H0017", char: "水", meaning: "물", sound: "수", level: "8", stroke: 4, radical: "水" },
  { id: "H0018", char: "木", meaning: "나무", sound: "목", level: "8", stroke: 4, radical: "木" },
  { id: "H0019", char: "金", meaning: "쇠", sound: "금", level: "8", stroke: 8, radical: "金" },
  { id: "H0020", char: "土", meaning: "흙", sound: "토", level: "8", stroke: 3, radical: "土" },
  { id: "H0021", char: "大", meaning: "큰", sound: "대", level: "8", stroke: 3, radical: "大" },
  { id: "H0022", char: "小", meaning: "작을", sound: "소", level: "8", stroke: 3, radical: "小" },
  { id: "H0023", char: "中", meaning: "가운데", sound: "중", level: "8", stroke: 4, radical: "丨" },
  { id: "H0024", char: "上", meaning: "윗", sound: "상", level: "8", stroke: 3, radical: "一" },
  { id: "H0025", char: "下", meaning: "아래", sound: "하", level: "8", stroke: 3, radical: "一" },
  { id: "H0026", char: "左", meaning: "왼", sound: "좌", level: "8", stroke: 5, radical: "工" },
  { id: "H0027", char: "右", meaning: "오른", sound: "우", level: "8", stroke: 5, radical: "口" },
  { id: "H0028", char: "東", meaning: "동녘", sound: "동", level: "8", stroke: 8, radical: "木" },
  { id: "H0029", char: "西", meaning: "서녘", sound: "서", level: "8", stroke: 6, radical: "襾" },
  { id: "H0030", char: "南", meaning: "남녘", sound: "남", level: "8", stroke: 9, radical: "十" },
  { id: "H0031", char: "北", meaning: "북녘", sound: "북", level: "8", stroke: 5, radical: "匕" },
  { id: "H0032", char: "山", meaning: "뫼", sound: "산", level: "8", stroke: 3, radical: "山" },
  { id: "H0033", char: "川", meaning: "내", sound: "천", level: "8", stroke: 3, radical: "川" },
  { id: "H0034", char: "江", meaning: "강", sound: "강", level: "8", stroke: 6, radical: "水" },
  { id: "H0035", char: "門", meaning: "문", sound: "문", level: "8", stroke: 8, radical: "門" },
  { id: "H0036", char: "人", meaning: "사람", sound: "인", level: "8", stroke: 2, radical: "人" },
  { id: "H0037", char: "女", meaning: "여자", sound: "여", level: "8", stroke: 3, radical: "女" },
  { id: "H0038", char: "子", meaning: "아들", sound: "자", level: "8", stroke: 3, radical: "子" },
  { id: "H0039", char: "王", meaning: "임금", sound: "왕", level: "8", stroke: 4, radical: "王" },
  { id: "H0040", char: "先", meaning: "먼저", sound: "선", level: "8", stroke: 6, radical: "儿" },
  { id: "H0041", char: "生", meaning: "날", sound: "생", level: "8", stroke: 5, radical: "生" },
  { id: "H0042", char: "學", meaning: "배울", sound: "학", level: "8", stroke: 16, radical: "子" },
  { id: "H0043", char: "校", meaning: "학교", sound: "교", level: "8", stroke: 10, radical: "木" },
  { id: "H0044", char: "父", meaning: "아비", sound: "부", level: "8", stroke: 4, radical: "父" },
  { id: "H0045", char: "母", meaning: "어미", sound: "모", level: "8", stroke: 5, radical: "母" },
  { id: "H0046", char: "兄", meaning: "형", sound: "형", level: "8", stroke: 5, radical: "儿" },
  { id: "H0047", char: "弟", meaning: "아우", sound: "제", level: "8", stroke: 7, radical: "弓" },
  { id: "H0048", char: "白", meaning: "흰", sound: "백", level: "8", stroke: 5, radical: "白" },
  { id: "H0049", char: "靑", meaning: "푸를", sound: "청", level: "8", stroke: 8, radical: "靑" },
  { id: "H0050", char: "年", meaning: "해", sound: "년", level: "8", stroke: 6, radical: "干" },

  // ===== 준7급 (50자) =====
  { id: "H0051", char: "力", meaning: "힘", sound: "력", level: "준7", stroke: 2, radical: "力" },
  { id: "H0052", char: "男", meaning: "사내", sound: "남", level: "준7", stroke: 7, radical: "田" },
  { id: "H0053", char: "立", meaning: "설", sound: "립", level: "준7", stroke: 5, radical: "立" },
  { id: "H0054", char: "天", meaning: "하늘", sound: "천", level: "준7", stroke: 4, radical: "大" },
  { id: "H0055", char: "氣", meaning: "기운", sound: "기", level: "준7", stroke: 10, radical: "气" },
  { id: "H0056", char: "出", meaning: "날", sound: "출", level: "준7", stroke: 5, radical: "凵" },
  { id: "H0057", char: "入", meaning: "들", sound: "입", level: "준7", stroke: 2, radical: "入" },
  { id: "H0058", char: "花", meaning: "꽃", sound: "화", level: "준7", stroke: 8, radical: "艸" },
  { id: "H0059", char: "草", meaning: "풀", sound: "초", level: "준7", stroke: 10, radical: "艸" },
  { id: "H0060", char: "石", meaning: "돌", sound: "석", level: "준7", stroke: 5, radical: "石" },
  { id: "H0061", char: "田", meaning: "밭", sound: "전", level: "준7", stroke: 5, radical: "田" },
  { id: "H0062", char: "里", meaning: "마을", sound: "리", level: "준7", stroke: 7, radical: "里" },
  { id: "H0063", char: "國", meaning: "나라", sound: "국", level: "준7", stroke: 11, radical: "囗" },
  { id: "H0064", char: "民", meaning: "백성", sound: "민", level: "준7", stroke: 5, radical: "氏" },
  { id: "H0065", char: "軍", meaning: "군사", sound: "군", level: "준7", stroke: 9, radical: "車" },
  { id: "H0066", char: "家", meaning: "집", sound: "가", level: "준7", stroke: 10, radical: "宀" },
  { id: "H0067", char: "室", meaning: "집", sound: "실", level: "준7", stroke: 9, radical: "宀" },
  { id: "H0068", char: "工", meaning: "장인", sound: "공", level: "준7", stroke: 3, radical: "工" },
  { id: "H0069", char: "場", meaning: "마당", sound: "장", level: "준7", stroke: 12, radical: "土" },
  { id: "H0070", char: "車", meaning: "수레", sound: "차", level: "준7", stroke: 7, radical: "車" },
  { id: "H0071", char: "長", meaning: "긴", sound: "장", level: "준7", stroke: 8, radical: "長" },
  { id: "H0072", char: "老", meaning: "늙을", sound: "노", level: "준7", stroke: 6, radical: "老" },
  { id: "H0073", char: "少", meaning: "적을", sound: "소", level: "준7", stroke: 4, radical: "小" },
  { id: "H0074", char: "市", meaning: "저자", sound: "시", level: "준7", stroke: 5, radical: "巾" },
  { id: "H0075", char: "村", meaning: "마을", sound: "촌", level: "준7", stroke: 7, radical: "木" },
  { id: "H0076", char: "寺", meaning: "절", sound: "사", level: "준7", stroke: 6, radical: "寸" },
  { id: "H0077", char: "自", meaning: "스스로", sound: "자", level: "준7", stroke: 6, radical: "自" },
  { id: "H0078", char: "心", meaning: "마음", sound: "심", level: "준7", stroke: 4, radical: "心" },
  { id: "H0079", char: "手", meaning: "손", sound: "수", level: "준7", stroke: 4, radical: "手" },
  { id: "H0080", char: "足", meaning: "발", sound: "족", level: "준7", stroke: 7, radical: "足" },
  { id: "H0081", char: "口", meaning: "입", sound: "구", level: "준7", stroke: 3, radical: "口" },
  { id: "H0082", char: "目", meaning: "눈", sound: "목", level: "준7", stroke: 5, radical: "目" },
  { id: "H0083", char: "耳", meaning: "귀", sound: "이", level: "준7", stroke: 6, radical: "耳" },
  { id: "H0084", char: "面", meaning: "낯", sound: "면", level: "준7", stroke: 9, radical: "面" },
  { id: "H0085", char: "身", meaning: "몸", sound: "신", level: "준7", stroke: 7, radical: "身" },
  { id: "H0086", char: "命", meaning: "목숨", sound: "명", level: "준7", stroke: 8, radical: "口" },
  { id: "H0087", char: "名", meaning: "이름", sound: "명", level: "준7", stroke: 6, radical: "口" },
  { id: "H0088", char: "字", meaning: "글자", sound: "자", level: "준7", stroke: 6, radical: "子" },
  { id: "H0089", char: "文", meaning: "글월", sound: "문", level: "준7", stroke: 4, radical: "文" },
  { id: "H0090", char: "書", meaning: "글", sound: "서", level: "준7", stroke: 10, radical: "曰" },
  { id: "H0091", char: "問", meaning: "물을", sound: "문", level: "준7", stroke: 11, radical: "口" },
  { id: "H0092", char: "答", meaning: "대답할", sound: "답", level: "준7", stroke: 12, radical: "竹" },
  { id: "H0093", char: "言", meaning: "말씀", sound: "언", level: "준7", stroke: 7, radical: "言" },
  { id: "H0094", char: "語", meaning: "말씀", sound: "어", level: "준7", stroke: 14, radical: "言" },
  { id: "H0095", char: "食", meaning: "밥", sound: "식", level: "준7", stroke: 9, radical: "食" },
  { id: "H0096", char: "色", meaning: "빛", sound: "색", level: "준7", stroke: 6, radical: "色" },
  { id: "H0097", char: "正", meaning: "바를", sound: "정", level: "준7", stroke: 5, radical: "止" },
  { id: "H0098", char: "直", meaning: "곧을", sound: "직", level: "준7", stroke: 8, radical: "目" },
  { id: "H0099", char: "安", meaning: "편안할", sound: "안", level: "준7", stroke: 6, radical: "宀" },
  { id: "H0100", char: "不", meaning: "아닐", sound: "불", level: "준7", stroke: 4, radical: "一" },

  // ===== 7급 (50자) =====
  { id: "H0101", char: "公", meaning: "공변될", sound: "공", level: "7", stroke: 4, radical: "八" },
  { id: "H0102", char: "共", meaning: "한가지", sound: "공", level: "7", stroke: 6, radical: "八" },
  { id: "H0103", char: "古", meaning: "옛", sound: "고", level: "7", stroke: 5, radical: "口" },
  { id: "H0104", char: "孝", meaning: "효도", sound: "효", level: "7", stroke: 7, radical: "子" },
  { id: "H0105", char: "光", meaning: "빛", sound: "광", level: "7", stroke: 6, radical: "儿" },
  { id: "H0106", char: "科", meaning: "과목", sound: "과", level: "7", stroke: 9, radical: "禾" },
  { id: "H0107", char: "果", meaning: "열매", sound: "과", level: "7", stroke: 8, radical: "木" },
  { id: "H0108", char: "交", meaning: "사귈", sound: "교", level: "7", stroke: 6, radical: "亠" },
  { id: "H0109", char: "敎", meaning: "가르칠", sound: "교", level: "7", stroke: 11, radical: "攴" },
  { id: "H0110", char: "記", meaning: "기록할", sound: "기", level: "7", stroke: 10, radical: "言" },
  { id: "H0111", char: "內", meaning: "안", sound: "내", level: "7", stroke: 4, radical: "入" },
  { id: "H0112", char: "農", meaning: "농사", sound: "농", level: "7", stroke: 13, radical: "辰" },
  { id: "H0113", char: "動", meaning: "움직일", sound: "동", level: "7", stroke: 11, radical: "力" },
  { id: "H0114", char: "同", meaning: "한가지", sound: "동", level: "7", stroke: 6, radical: "口" },
  { id: "H0115", char: "道", meaning: "길", sound: "도", level: "7", stroke: 13, radical: "辵" },
  { id: "H0116", char: "讀", meaning: "읽을", sound: "독", level: "7", stroke: 22, radical: "言" },
  { id: "H0117", char: "落", meaning: "떨어질", sound: "락", level: "7", stroke: 13, radical: "艸" },
  { id: "H0118", char: "來", meaning: "올", sound: "래", level: "7", stroke: 8, radical: "人" },
  { id: "H0119", char: "冬", meaning: "겨울", sound: "동", level: "7", stroke: 5, radical: "冫" },
  { id: "H0120", char: "明", meaning: "밝을", sound: "명", level: "7", stroke: 8, radical: "日" },
  { id: "H0121", char: "方", meaning: "모", sound: "방", level: "7", stroke: 4, radical: "方" },
  { id: "H0122", char: "放", meaning: "놓을", sound: "방", level: "7", stroke: 8, radical: "攴" },
  { id: "H0123", char: "別", meaning: "나눌", sound: "별", level: "7", stroke: 7, radical: "刀" },
  { id: "H0124", char: "病", meaning: "병", sound: "병", level: "7", stroke: 10, radical: "疒" },
  { id: "H0125", char: "步", meaning: "걸음", sound: "보", level: "7", stroke: 7, radical: "止" },
  { id: "H0126", char: "夫", meaning: "지아비", sound: "부", level: "7", stroke: 4, radical: "大" },
  { id: "H0127", char: "分", meaning: "나눌", sound: "분", level: "7", stroke: 4, radical: "刀" },
  { id: "H0128", char: "社", meaning: "모일", sound: "사", level: "7", stroke: 8, radical: "示" },
  { id: "H0129", char: "事", meaning: "일", sound: "사", level: "7", stroke: 8, radical: "亅" },
  { id: "H0130", char: "寫", meaning: "베낄", sound: "사", level: "7", stroke: 15, radical: "宀" },
  { id: "H0131", char: "算", meaning: "셀", sound: "산", level: "7", stroke: 14, radical: "竹" },
  { id: "H0132", char: "成", meaning: "이룰", sound: "성", level: "7", stroke: 7, radical: "戈" },
  { id: "H0133", char: "世", meaning: "인간", sound: "세", level: "7", stroke: 5, radical: "一" },
  { id: "H0134", char: "所", meaning: "바", sound: "소", level: "7", stroke: 8, radical: "戶" },
  { id: "H0135", char: "信", meaning: "믿을", sound: "신", level: "7", stroke: 9, radical: "人" },
  { id: "H0136", char: "新", meaning: "새", sound: "신", level: "7", stroke: 13, radical: "斤" },
  { id: "H0137", char: "午", meaning: "낮", sound: "오", level: "7", stroke: 4, radical: "十" },
  { id: "H0138", char: "外", meaning: "바깥", sound: "외", level: "7", stroke: 5, radical: "夕" },
  { id: "H0139", char: "用", meaning: "쓸", sound: "용", level: "7", stroke: 5, radical: "用" },
  { id: "H0140", char: "友", meaning: "벗", sound: "우", level: "7", stroke: 4, radical: "又" },
  { id: "H0141", char: "運", meaning: "움직일", sound: "운", level: "7", stroke: 12, radical: "辵" },
  { id: "H0142", char: "元", meaning: "으뜸", sound: "원", level: "7", stroke: 4, radical: "儿" },
  { id: "H0143", char: "遠", meaning: "멀", sound: "원", level: "7", stroke: 13, radical: "辵" },
  { id: "H0144", char: "有", meaning: "있을", sound: "유", level: "7", stroke: 6, radical: "月" },
  { id: "H0145", char: "育", meaning: "기를", sound: "육", level: "7", stroke: 8, radical: "肉" },
  { id: "H0146", char: "點", meaning: "점", sound: "점", level: "7", stroke: 17, radical: "黑" },
  { id: "H0147", char: "主", meaning: "임금", sound: "주", level: "7", stroke: 5, radical: "丶" },
  { id: "H0148", char: "注", meaning: "부을", sound: "주", level: "7", stroke: 8, radical: "水" },
  { id: "H0149", char: "春", meaning: "봄", sound: "춘", level: "7", stroke: 9, radical: "日" },
  { id: "H0150", char: "夏", meaning: "여름", sound: "하", level: "7", stroke: 10, radical: "夂" },

  // ===== 준6급 (75자) =====
  { id: "H0151", char: "歌", meaning: "노래", sound: "가", level: "준6", stroke: 14, radical: "欠" },
  { id: "H0152", char: "各", meaning: "각각", sound: "각", level: "준6", stroke: 6, radical: "口" },
  { id: "H0153", char: "間", meaning: "사이", sound: "간", level: "준6", stroke: 12, radical: "門" },
  { id: "H0154", char: "感", meaning: "느낄", sound: "감", level: "준6", stroke: 13, radical: "心" },
  { id: "H0155", char: "開", meaning: "열", sound: "개", level: "준6", stroke: 12, radical: "門" },
  { id: "H0156", char: "客", meaning: "손", sound: "객", level: "준6", stroke: 9, radical: "宀" },
  { id: "H0157", char: "去", meaning: "갈", sound: "거", level: "준6", stroke: 5, radical: "厶" },
  { id: "H0158", char: "建", meaning: "세울", sound: "건", level: "준6", stroke: 9, radical: "廴" },
  { id: "H0159", char: "見", meaning: "볼", sound: "견", level: "준6", stroke: 7, radical: "見" },
  { id: "H0160", char: "決", meaning: "결단할", sound: "결", level: "준6", stroke: 7, radical: "水" },
  { id: "H0161", char: "結", meaning: "맺을", sound: "결", level: "준6", stroke: 12, radical: "糸" },
  { id: "H0162", char: "京", meaning: "서울", sound: "경", level: "준6", stroke: 8, radical: "亠" },
  { id: "H0163", char: "計", meaning: "셀", sound: "계", level: "준6", stroke: 9, radical: "言" },
  { id: "H0164", char: "告", meaning: "고할", sound: "고", level: "준6", stroke: 7, radical: "口" },
  { id: "H0165", char: "空", meaning: "빌", sound: "공", level: "준6", stroke: 8, radical: "穴" },
  { id: "H0166", char: "過", meaning: "지날", sound: "과", level: "준6", stroke: 12, radical: "辵" },
  { id: "H0167", char: "官", meaning: "벼슬", sound: "관", level: "준6", stroke: 8, radical: "宀" },
  { id: "H0168", char: "觀", meaning: "볼", sound: "관", level: "준6", stroke: 25, radical: "見" },
  { id: "H0169", char: "廣", meaning: "넓을", sound: "광", level: "준6", stroke: 15, radical: "广" },
  { id: "H0170", char: "球", meaning: "공", sound: "구", level: "준6", stroke: 11, radical: "玉" },
  { id: "H0171", char: "近", meaning: "가까울", sound: "근", level: "준6", stroke: 7, radical: "辵" },
  { id: "H0172", char: "急", meaning: "급할", sound: "급", level: "준6", stroke: 9, radical: "心" },
  { id: "H0173", char: "級", meaning: "등급", sound: "급", level: "준6", stroke: 10, radical: "糸" },
  { id: "H0174", char: "達", meaning: "통달할", sound: "달", level: "준6", stroke: 12, radical: "辵" },
  { id: "H0175", char: "堂", meaning: "집", sound: "당", level: "준6", stroke: 11, radical: "土" },
  { id: "H0176", char: "待", meaning: "기다릴", sound: "대", level: "준6", stroke: 9, radical: "彳" },
  { id: "H0177", char: "代", meaning: "대신할", sound: "대", level: "준6", stroke: 5, radical: "人" },
  { id: "H0178", char: "對", meaning: "대할", sound: "대", level: "준6", stroke: 14, radical: "寸" },
  { id: "H0179", char: "德", meaning: "큰", sound: "덕", level: "준6", stroke: 15, radical: "彳" },
  { id: "H0180", char: "度", meaning: "법도", sound: "도", level: "준6", stroke: 9, radical: "广" },
  { id: "H0181", char: "圖", meaning: "그림", sound: "도", level: "준6", stroke: 14, radical: "囗" },
  { id: "H0182", char: "頭", meaning: "머리", sound: "두", level: "준6", stroke: 16, radical: "頁" },
  { id: "H0183", char: "登", meaning: "오를", sound: "등", level: "준6", stroke: 12, radical: "癶" },
  { id: "H0184", char: "等", meaning: "무리", sound: "등", level: "준6", stroke: 12, radical: "竹" },
  { id: "H0185", char: "樂", meaning: "즐길", sound: "락", level: "준6", stroke: 15, radical: "木" },
  { id: "H0186", char: "利", meaning: "이로울", sound: "리", level: "준6", stroke: 7, radical: "刀" },
  { id: "H0187", char: "理", meaning: "다스릴", sound: "리", level: "준6", stroke: 11, radical: "玉" },
  { id: "H0188", char: "林", meaning: "수풀", sound: "림", level: "준6", stroke: 8, radical: "木" },
  { id: "H0189", char: "馬", meaning: "말", sound: "마", level: "준6", stroke: 10, radical: "馬" },
  { id: "H0190", char: "每", meaning: "매양", sound: "매", level: "준6", stroke: 7, radical: "母" },
  { id: "H0191", char: "末", meaning: "끝", sound: "말", level: "준6", stroke: 5, radical: "木" },
  { id: "H0192", char: "物", meaning: "만물", sound: "물", level: "준6", stroke: 8, radical: "牛" },
  { id: "H0193", char: "美", meaning: "아름다울", sound: "미", level: "준6", stroke: 9, radical: "羊" },
  { id: "H0194", char: "反", meaning: "돌이킬", sound: "반", level: "준6", stroke: 4, radical: "又" },
  { id: "H0195", char: "半", meaning: "반", sound: "반", level: "준6", stroke: 5, radical: "十" },
  { id: "H0196", char: "發", meaning: "필", sound: "발", level: "준6", stroke: 12, radical: "癶" },
  { id: "H0197", char: "返", meaning: "돌아올", sound: "반", level: "준6", stroke: 7, radical: "辵" },
  { id: "H0198", char: "飯", meaning: "밥", sound: "반", level: "준6", stroke: 12, radical: "食" },
  { id: "H0199", char: "番", meaning: "차례", sound: "번", level: "준6", stroke: 12, radical: "田" },
  { id: "H0200", char: "法", meaning: "법", sound: "법", level: "준6", stroke: 8, radical: "水" },
  { id: "H0201", char: "平", meaning: "평평할", sound: "평", level: "준6", stroke: 5, radical: "干" },
  { id: "H0202", char: "部", meaning: "떼", sound: "부", level: "준6", stroke: 11, radical: "邑" },
  { id: "H0203", char: "福", meaning: "복", sound: "복", level: "준6", stroke: 14, radical: "示" },
  { id: "H0204", char: "本", meaning: "근본", sound: "본", level: "준6", stroke: 5, radical: "木" },
  { id: "H0205", char: "漢", meaning: "한수", sound: "한", level: "준6", stroke: 14, radical: "水" },
  { id: "H0206", char: "海", meaning: "바다", sound: "해", level: "준6", stroke: 10, radical: "水" },
  { id: "H0207", char: "幸", meaning: "다행", sound: "행", level: "준6", stroke: 8, radical: "干" },
  { id: "H0208", char: "形", meaning: "모양", sound: "형", level: "준6", stroke: 7, radical: "彡" },
  { id: "H0209", char: "會", meaning: "모일", sound: "회", level: "준6", stroke: 13, radical: "曰" },
  { id: "H0210", char: "後", meaning: "뒤", sound: "후", level: "준6", stroke: 9, radical: "彳" },
  { id: "H0211", char: "化", meaning: "될", sound: "화", level: "준6", stroke: 4, radical: "匕" },
  { id: "H0212", char: "話", meaning: "말씀", sound: "화", level: "준6", stroke: 13, radical: "言" },
  { id: "H0213", char: "孫", meaning: "손자", sound: "손", level: "준6", stroke: 10, radical: "子" },
  { id: "H0214", char: "集", meaning: "모을", sound: "집", level: "준6", stroke: 12, radical: "隹" },
  { id: "H0215", char: "靜", meaning: "고요할", sound: "정", level: "준6", stroke: 16, radical: "靑" },
  { id: "H0216", char: "和", meaning: "화할", sound: "화", level: "준6", stroke: 8, radical: "口" },
  { id: "H0217", char: "活", meaning: "살", sound: "활", level: "준6", stroke: 10, radical: "水" },
  { id: "H0218", char: "回", meaning: "돌", sound: "회", level: "준6", stroke: 6, radical: "囗" },
  { id: "H0219", char: "紙", meaning: "종이", sound: "지", level: "준6", stroke: 10, radical: "糸" },
  { id: "H0220", char: "始", meaning: "비로소", sound: "시", level: "준6", stroke: 8, radical: "女" },
  { id: "H0221", char: "便", meaning: "편할", sound: "편", level: "준6", stroke: 9, radical: "人" },
  { id: "H0222", char: "全", meaning: "온전할", sound: "전", level: "준6", stroke: 6, radical: "入" },
  { id: "H0223", char: "現", meaning: "나타날", sound: "현", level: "준6", stroke: 11, radical: "玉" },
  { id: "H0224", char: "秋", meaning: "가을", sound: "추", level: "준6", stroke: 9, radical: "禾" },
  { id: "H0225", char: "節", meaning: "마디", sound: "절", level: "준6", stroke: 13, radical: "竹" },

  // ===== 6급 (75자) =====
  { id: "H0226", char: "價", meaning: "값", sound: "가", level: "6", stroke: 15, radical: "人" },
  { id: "H0227", char: "角", meaning: "뿔", sound: "각", level: "6", stroke: 7, radical: "角" },
  { id: "H0228", char: "强", meaning: "강할", sound: "강", level: "6", stroke: 11, radical: "弓" },
  { id: "H0229", char: "件", meaning: "물건", sound: "건", level: "6", stroke: 6, radical: "人" },
  { id: "H0230", char: "格", meaning: "격식", sound: "격", level: "6", stroke: 10, radical: "木" },
  { id: "H0231", char: "意", meaning: "뜻", sound: "의", level: "6", stroke: 13, radical: "心" },
  { id: "H0232", char: "義", meaning: "옳을", sound: "의", level: "6", stroke: 13, radical: "羊" },
  { id: "H0233", char: "議", meaning: "의논할", sound: "의", level: "6", stroke: 20, radical: "言" },
  { id: "H0234", char: "根", meaning: "뿌리", sound: "근", level: "6", stroke: 10, radical: "木" },
  { id: "H0235", char: "期", meaning: "기약할", sound: "기", level: "6", stroke: 12, radical: "月" },
  { id: "H0236", char: "氏", meaning: "성씨", sound: "씨", level: "6", stroke: 4, radical: "氏" },
  { id: "H0237", char: "然", meaning: "그럴", sound: "연", level: "6", stroke: 12, radical: "火" },
  { id: "H0238", char: "約", meaning: "맺을", sound: "약", level: "6", stroke: 9, radical: "糸" },
  { id: "H0239", char: "陽", meaning: "볕", sound: "양", level: "6", stroke: 12, radical: "阜" },
  { id: "H0240", char: "洋", meaning: "큰바다", sound: "양", level: "6", stroke: 9, radical: "水" },
  { id: "H0241", char: "億", meaning: "억", sound: "억", level: "6", stroke: 15, radical: "人" },
  { id: "H0242", char: "容", meaning: "얼굴", sound: "용", level: "6", stroke: 10, radical: "宀" },
  { id: "H0243", char: "溫", meaning: "따뜻할", sound: "온", level: "6", stroke: 13, radical: "水" },
  { id: "H0244", char: "完", meaning: "완전할", sound: "완", level: "6", stroke: 7, radical: "宀" },
  { id: "H0245", char: "銀", meaning: "은", sound: "은", level: "6", stroke: 14, radical: "金" },
  { id: "H0246", char: "院", meaning: "집", sound: "원", level: "6", stroke: 10, radical: "阜" },
  { id: "H0247", char: "位", meaning: "자리", sound: "위", level: "6", stroke: 7, radical: "人" },
  { id: "H0248", char: "引", meaning: "끌", sound: "인", level: "6", stroke: 4, radical: "弓" },
  { id: "H0249", char: "因", meaning: "인할", sound: "인", level: "6", stroke: 6, radical: "囗" },
  { id: "H0250", char: "仁", meaning: "어질", sound: "인", level: "6", stroke: 4, radical: "人" },
  { id: "H0251", char: "作", meaning: "지을", sound: "작", level: "6", stroke: 7, radical: "人" },
  { id: "H0252", char: "才", meaning: "재주", sound: "재", level: "6", stroke: 3, radical: "手" },
  { id: "H0253", char: "的", meaning: "과녁", sound: "적", level: "6", stroke: 8, radical: "白" },
  { id: "H0254", char: "切", meaning: "끊을", sound: "절", level: "6", stroke: 4, radical: "刀" },
  { id: "H0255", char: "戰", meaning: "싸울", sound: "전", level: "6", stroke: 16, radical: "戈" },
  { id: "H0256", char: "定", meaning: "정할", sound: "정", level: "6", stroke: 8, radical: "宀" },
  { id: "H0257", char: "精", meaning: "정할", sound: "정", level: "6", stroke: 14, radical: "米" },
  { id: "H0258", char: "政", meaning: "정사", sound: "정", level: "6", stroke: 9, radical: "攴" },
  { id: "H0259", char: "第", meaning: "차례", sound: "제", level: "6", stroke: 11, radical: "竹" },
  { id: "H0260", char: "題", meaning: "제목", sound: "제", level: "6", stroke: 18, radical: "頁" },
  { id: "H0261", char: "祖", meaning: "할아비", sound: "조", level: "6", stroke: 10, radical: "示" },
  { id: "H0262", char: "族", meaning: "겨레", sound: "족", level: "6", stroke: 11, radical: "方" },
  { id: "H0263", char: "存", meaning: "있을", sound: "존", level: "6", stroke: 6, radical: "子" },
  { id: "H0264", char: "終", meaning: "마칠", sound: "종", level: "6", stroke: 11, radical: "糸" },
  { id: "H0265", char: "種", meaning: "씨", sound: "종", level: "6", stroke: 14, radical: "禾" },
  { id: "H0266", char: "進", meaning: "나아갈", sound: "진", level: "6", stroke: 12, radical: "辵" },
  { id: "H0267", char: "着", meaning: "붙을", sound: "착", level: "6", stroke: 12, radical: "目" },
  { id: "H0268", char: "責", meaning: "꾸짖을", sound: "책", level: "6", stroke: 11, radical: "貝" },
  { id: "H0269", char: "處", meaning: "곳", sound: "처", level: "6", stroke: 11, radical: "虍" },
  { id: "H0270", char: "初", meaning: "처음", sound: "초", level: "6", stroke: 7, radical: "刀" },
  { id: "H0271", char: "最", meaning: "가장", sound: "최", level: "6", stroke: 12, radical: "曰" },
  { id: "H0272", char: "充", meaning: "채울", sound: "충", level: "6", stroke: 6, radical: "儿" },
  { id: "H0273", char: "層", meaning: "층", sound: "층", level: "6", stroke: 15, radical: "尸" },
  { id: "H0274", char: "治", meaning: "다스릴", sound: "치", level: "6", stroke: 8, radical: "水" },
  { id: "H0275", char: "親", meaning: "어버이", sound: "친", level: "6", stroke: 16, radical: "見" },
  { id: "H0276", char: "太", meaning: "클", sound: "태", level: "6", stroke: 4, radical: "大" },
  { id: "H0277", char: "特", meaning: "특별할", sound: "특", level: "6", stroke: 10, radical: "牛" },
  { id: "H0278", char: "通", meaning: "통할", sound: "통", level: "6", stroke: 11, radical: "辵" },
  { id: "H0279", char: "退", meaning: "물러날", sound: "퇴", level: "6", stroke: 10, radical: "辵" },
  { id: "H0280", char: "表", meaning: "겉", sound: "표", level: "6", stroke: 8, radical: "衣" },
  { id: "H0281", char: "品", meaning: "물건", sound: "품", level: "6", stroke: 9, radical: "口" },
  { id: "H0282", char: "必", meaning: "반드시", sound: "필", level: "6", stroke: 5, radical: "心" },
  { id: "H0283", char: "河", meaning: "물", sound: "하", level: "6", stroke: 8, radical: "水" },
  { id: "H0284", char: "限", meaning: "한할", sound: "한", level: "6", stroke: 9, radical: "阜" },
  { id: "H0285", char: "港", meaning: "항구", sound: "항", level: "6", stroke: 12, radical: "水" },
  { id: "H0286", char: "解", meaning: "풀", sound: "해", level: "6", stroke: 13, radical: "角" },
  { id: "H0287", char: "向", meaning: "향할", sound: "향", level: "6", stroke: 6, radical: "口" },
  { id: "H0288", char: "許", meaning: "허락할", sound: "허", level: "6", stroke: 11, radical: "言" },
  { id: "H0289", char: "號", meaning: "이름", sound: "호", level: "6", stroke: 13, radical: "虍" },
  { id: "H0290", char: "畫", meaning: "그림", sound: "화", level: "6", stroke: 12, radical: "田" },
  { id: "H0291", char: "效", meaning: "본받을", sound: "효", level: "6", stroke: 10, radical: "攴" },
  { id: "H0292", char: "訓", meaning: "가르칠", sound: "훈", level: "6", stroke: 10, radical: "言" },
  { id: "H0293", char: "興", meaning: "일어날", sound: "흥", level: "6", stroke: 16, radical: "臼" },
  { id: "H0294", char: "內", meaning: "안", sound: "내", level: "6", stroke: 4, radical: "入" },
  { id: "H0295", char: "正", meaning: "바를", sound: "정", level: "6", stroke: 5, radical: "止" },
  { id: "H0296", char: "道", meaning: "길", sound: "도", level: "6", stroke: 13, radical: "辵" },
  { id: "H0297", char: "動", meaning: "움직일", sound: "동", level: "6", stroke: 11, radical: "力" },
  { id: "H0298", char: "力", meaning: "힘", sound: "력", level: "6", stroke: 2, radical: "力" },
  { id: "H0299", char: "結", meaning: "맺을", sound: "결", level: "6", stroke: 12, radical: "糸" },
  { id: "H0300", char: "生", meaning: "날", sound: "생", level: "6", stroke: 5, radical: "生" },
];

export const wordData: HanjaWord[] = [
  // ===== 8급 단어 =====
  { id: "W0001", hanja: "學校", reading: "학교", meaning: "학교", level: "8", chars: ["H0042", "H0043"] },
  { id: "W0002", hanja: "學生", reading: "학생", meaning: "학생", level: "8", chars: ["H0042", "H0041"] },
  { id: "W0003", hanja: "先生", reading: "선생", meaning: "선생님", level: "8", chars: ["H0040", "H0041"] },
  { id: "W0004", hanja: "父母", reading: "부모", meaning: "부모", level: "8", chars: ["H0044", "H0045"] },
  { id: "W0005", hanja: "兄弟", reading: "형제", meaning: "형제", level: "8", chars: ["H0046", "H0047"] },
  { id: "W0006", hanja: "東西", reading: "동서", meaning: "동쪽과 서쪽", level: "8", chars: ["H0028", "H0029"] },
  { id: "W0007", hanja: "南北", reading: "남북", meaning: "남쪽과 북쪽", level: "8", chars: ["H0030", "H0031"] },
  { id: "W0008", hanja: "上下", reading: "상하", meaning: "위와 아래", level: "8", chars: ["H0024", "H0025"] },
  { id: "W0009", hanja: "左右", reading: "좌우", meaning: "왼쪽과 오른쪽", level: "8", chars: ["H0026", "H0027"] },
  { id: "W0010", hanja: "大小", reading: "대소", meaning: "크고 작음", level: "8", chars: ["H0021", "H0022"] },
  { id: "W0011", hanja: "大人", reading: "대인", meaning: "어른", level: "8", chars: ["H0021", "H0036"] },
  { id: "W0012", hanja: "中學", reading: "중학", meaning: "중학교", level: "8", chars: ["H0023", "H0042"] },
  { id: "W0013", hanja: "山川", reading: "산천", meaning: "산과 내", level: "8", chars: ["H0032", "H0033"] },
  { id: "W0014", hanja: "山水", reading: "산수", meaning: "산과 물, 풍경", level: "8", chars: ["H0032", "H0017"] },
  { id: "W0015", hanja: "江山", reading: "강산", meaning: "강과 산, 국토", level: "8", chars: ["H0034", "H0032"] },
  { id: "W0016", hanja: "日月", reading: "일월", meaning: "해와 달", level: "8", chars: ["H0014", "H0015"] },
  { id: "W0017", hanja: "火山", reading: "화산", meaning: "화산", level: "8", chars: ["H0016", "H0032"] },
  { id: "W0018", hanja: "水木", reading: "수목", meaning: "나무", level: "8", chars: ["H0017", "H0018"] },
  { id: "W0019", hanja: "金土", reading: "금토", meaning: "금요일과 토요일", level: "8", chars: ["H0019", "H0020"] },
  { id: "W0020", hanja: "王子", reading: "왕자", meaning: "왕의 아들", level: "8", chars: ["H0039", "H0038"] },
  { id: "W0021", hanja: "女子", reading: "여자", meaning: "여자", level: "8", chars: ["H0037", "H0038"] },
  { id: "W0022", hanja: "子女", reading: "자녀", meaning: "아들과 딸", level: "8", chars: ["H0038", "H0037"] },
  { id: "W0023", hanja: "靑年", reading: "청년", meaning: "젊은이", level: "8", chars: ["H0049", "H0050"] },
  { id: "W0024", hanja: "白人", reading: "백인", meaning: "백인", level: "8", chars: ["H0048", "H0036"] },
  { id: "W0025", hanja: "百萬", reading: "백만", meaning: "백만", level: "8", chars: ["H0011", "H0013"] },

  // ===== 준7급 단어 =====
  { id: "W0026", hanja: "國民", reading: "국민", meaning: "국민", level: "준7", chars: ["H0063", "H0064"] },
  { id: "W0027", hanja: "國家", reading: "국가", meaning: "국가", level: "준7", chars: ["H0063", "H0066"] },
  { id: "W0028", hanja: "國軍", reading: "국군", meaning: "국군", level: "준7", chars: ["H0063", "H0065"] },
  { id: "W0029", hanja: "家長", reading: "가장", meaning: "집안의 어른", level: "준7", chars: ["H0066", "H0071"] },
  { id: "W0030", hanja: "男女", reading: "남녀", meaning: "남자와 여자", level: "준7", chars: ["H0052", "H0037"] },
  { id: "W0031", hanja: "男子", reading: "남자", meaning: "남자", level: "준7", chars: ["H0052", "H0038"] },
  { id: "W0032", hanja: "天氣", reading: "천기", meaning: "날씨", level: "준7", chars: ["H0054", "H0055"] },
  { id: "W0033", hanja: "出入", reading: "출입", meaning: "드나듦", level: "준7", chars: ["H0056", "H0057"] },
  { id: "W0034", hanja: "花草", reading: "화초", meaning: "꽃과 풀", level: "준7", chars: ["H0058", "H0059"] },
  { id: "W0035", hanja: "田里", reading: "전리", meaning: "논밭과 마을", level: "준7", chars: ["H0061", "H0062"] },
  { id: "W0036", hanja: "工場", reading: "공장", meaning: "공장", level: "준7", chars: ["H0068", "H0069"] },
  { id: "W0037", hanja: "市場", reading: "시장", meaning: "시장", level: "준7", chars: ["H0074", "H0069"] },
  { id: "W0038", hanja: "市民", reading: "시민", meaning: "시민", level: "준7", chars: ["H0074", "H0064"] },
  { id: "W0039", hanja: "老少", reading: "노소", meaning: "늙은이와 젊은이", level: "준7", chars: ["H0072", "H0073"] },
  { id: "W0040", hanja: "老人", reading: "노인", meaning: "노인", level: "준7", chars: ["H0072", "H0036"] },
  { id: "W0041", hanja: "少年", reading: "소년", meaning: "소년", level: "준7", chars: ["H0073", "H0050"] },
  { id: "W0042", hanja: "自立", reading: "자립", meaning: "자립", level: "준7", chars: ["H0077", "H0053"] },
  { id: "W0043", hanja: "心身", reading: "심신", meaning: "마음과 몸", level: "준7", chars: ["H0078", "H0085"] },
  { id: "W0044", hanja: "手足", reading: "수족", meaning: "손발", level: "준7", chars: ["H0079", "H0080"] },
  { id: "W0045", hanja: "耳目", reading: "이목", meaning: "귀와 눈", level: "준7", chars: ["H0083", "H0082"] },
  { id: "W0046", hanja: "名字", reading: "명자", meaning: "이름과 자", level: "준7", chars: ["H0087", "H0088"] },
  { id: "W0047", hanja: "文字", reading: "문자", meaning: "문자", level: "준7", chars: ["H0089", "H0088"] },
  { id: "W0048", hanja: "問答", reading: "문답", meaning: "묻고 대답함", level: "준7", chars: ["H0091", "H0092"] },
  { id: "W0049", hanja: "言語", reading: "언어", meaning: "언어", level: "준7", chars: ["H0093", "H0094"] },
  { id: "W0050", hanja: "食口", reading: "식구", meaning: "식구, 가족", level: "준7", chars: ["H0095", "H0081"] },
  { id: "W0051", hanja: "正直", reading: "정직", meaning: "정직", level: "준7", chars: ["H0097", "H0098"] },
  { id: "W0052", hanja: "安心", reading: "안심", meaning: "안심", level: "준7", chars: ["H0099", "H0078"] },
  { id: "W0053", hanja: "不正", reading: "부정", meaning: "부정", level: "준7", chars: ["H0100", "H0097"] },
  { id: "W0054", hanja: "力士", reading: "역사", meaning: "힘이 센 사람", level: "준7", chars: ["H0051", "H0041"] },
  { id: "W0055", hanja: "村長", reading: "촌장", meaning: "촌장", level: "준7", chars: ["H0075", "H0071"] },

  // ===== 7급 단어 =====
  { id: "W0056", hanja: "公共", reading: "공공", meaning: "공공", level: "7", chars: ["H0101", "H0102"] },
  { id: "W0057", hanja: "古今", reading: "고금", meaning: "옛날과 지금", level: "7", chars: ["H0103", "H0019"] },
  { id: "W0058", hanja: "交友", reading: "교우", meaning: "벗과 사귐", level: "7", chars: ["H0108", "H0140"] },
  { id: "W0059", hanja: "敎育", reading: "교육", meaning: "교육", level: "7", chars: ["H0109", "H0145"] },
  { id: "W0060", hanja: "記事", reading: "기사", meaning: "기사", level: "7", chars: ["H0110", "H0129"] },
  { id: "W0061", hanja: "內外", reading: "내외", meaning: "안과 밖", level: "7", chars: ["H0111", "H0138"] },
  { id: "W0062", hanja: "農民", reading: "농민", meaning: "농민", level: "7", chars: ["H0112", "H0064"] },
  { id: "W0063", hanja: "動物", reading: "동물", meaning: "동물", level: "7", chars: ["H0113", "H0192"] },
  { id: "W0064", hanja: "同生", reading: "동생", meaning: "동생", level: "7", chars: ["H0114", "H0041"] },
  { id: "W0065", hanja: "讀書", reading: "독서", meaning: "독서", level: "7", chars: ["H0116", "H0090"] },
  { id: "W0066", hanja: "明日", reading: "명일", meaning: "내일", level: "7", chars: ["H0120", "H0014"] },
  { id: "W0067", hanja: "方向", reading: "방향", meaning: "방향", level: "7", chars: ["H0121", "H0287"] },
  { id: "W0068", hanja: "別名", reading: "별명", meaning: "별명", level: "7", chars: ["H0123", "H0087"] },
  { id: "W0069", hanja: "病院", reading: "병원", meaning: "병원", level: "7", chars: ["H0124", "H0246"] },
  { id: "W0070", hanja: "夫人", reading: "부인", meaning: "부인", level: "7", chars: ["H0126", "H0036"] },
  { id: "W0071", hanja: "社會", reading: "사회", meaning: "사회", level: "7", chars: ["H0128", "H0209"] },
  { id: "W0072", hanja: "新聞", reading: "신문", meaning: "신문", level: "7", chars: ["H0136", "H0091"] },
  { id: "W0073", hanja: "運動", reading: "운동", meaning: "운동", level: "7", chars: ["H0141", "H0113"] },
  { id: "W0074", hanja: "有名", reading: "유명", meaning: "유명", level: "7", chars: ["H0144", "H0087"] },
  { id: "W0075", hanja: "主人", reading: "주인", meaning: "주인", level: "7", chars: ["H0147", "H0036"] },
  { id: "W0076", hanja: "成功", reading: "성공", meaning: "성공", level: "7", chars: ["H0132", "H0101"] },
  { id: "W0077", hanja: "世上", reading: "세상", meaning: "세상", level: "7", chars: ["H0133", "H0024"] },
  { id: "W0078", hanja: "分明", reading: "분명", meaning: "분명", level: "7", chars: ["H0127", "H0120"] },
  { id: "W0079", hanja: "用事", reading: "용사", meaning: "용무", level: "7", chars: ["H0139", "H0129"] },
  { id: "W0080", hanja: "春夏", reading: "춘하", meaning: "봄과 여름", level: "7", chars: ["H0149", "H0150"] },

  // ===== 준6급 단어 =====
  { id: "W0081", hanja: "感動", reading: "감동", meaning: "감동", level: "준6", chars: ["H0154", "H0113"] },
  { id: "W0082", hanja: "開始", reading: "개시", meaning: "개시, 시작", level: "준6", chars: ["H0155", "H0220"] },
  { id: "W0083", hanja: "決定", reading: "결정", meaning: "결정", level: "준6", chars: ["H0160", "H0256"] },
  { id: "W0084", hanja: "結果", reading: "결과", meaning: "결과", level: "준6", chars: ["H0161", "H0107"] },
  { id: "W0085", hanja: "計算", reading: "계산", meaning: "계산", level: "준6", chars: ["H0163", "H0131"] },
  { id: "W0086", hanja: "空間", reading: "공간", meaning: "공간", level: "준6", chars: ["H0165", "H0153"] },
  { id: "W0087", hanja: "觀光", reading: "관광", meaning: "관광", level: "준6", chars: ["H0168", "H0105"] },
  { id: "W0088", hanja: "廣告", reading: "광고", meaning: "광고", level: "준6", chars: ["H0169", "H0164"] },
  { id: "W0089", hanja: "急行", reading: "급행", meaning: "급행", level: "준6", chars: ["H0172", "H0207"] },
  { id: "W0090", hanja: "代表", reading: "대표", meaning: "대표", level: "준6", chars: ["H0177", "H0280"] },
  { id: "W0091", hanja: "圖書", reading: "도서", meaning: "도서", level: "준6", chars: ["H0181", "H0090"] },
  { id: "W0092", hanja: "登山", reading: "등산", meaning: "등산", level: "준6", chars: ["H0183", "H0032"] },
  { id: "W0093", hanja: "理由", reading: "이유", meaning: "이유", level: "준6", chars: ["H0187", "H0144"] },
  { id: "W0094", hanja: "美人", reading: "미인", meaning: "미인", level: "준6", chars: ["H0193", "H0036"] },
  { id: "W0095", hanja: "半分", reading: "반분", meaning: "절반", level: "준6", chars: ["H0195", "H0127"] },
  { id: "W0096", hanja: "發明", reading: "발명", meaning: "발명", level: "준6", chars: ["H0196", "H0120"] },
  { id: "W0097", hanja: "法律", reading: "법률", meaning: "법률", level: "준6", chars: ["H0200", "H0053"] },
  { id: "W0098", hanja: "平和", reading: "평화", meaning: "평화", level: "준6", chars: ["H0201", "H0216"] },
  { id: "W0099", hanja: "本來", reading: "본래", meaning: "본래", level: "준6", chars: ["H0204", "H0118"] },
  { id: "W0100", hanja: "漢字", reading: "한자", meaning: "한자", level: "준6", chars: ["H0205", "H0088"] },
  { id: "W0101", hanja: "海外", reading: "해외", meaning: "해외", level: "준6", chars: ["H0206", "H0138"] },
  { id: "W0102", hanja: "幸福", reading: "행복", meaning: "행복", level: "준6", chars: ["H0207", "H0203"] },
  { id: "W0103", hanja: "會話", reading: "회화", meaning: "회화", level: "준6", chars: ["H0209", "H0212"] },
  { id: "W0104", hanja: "活動", reading: "활동", meaning: "활동", level: "준6", chars: ["H0217", "H0113"] },
  { id: "W0105", hanja: "歌手", reading: "가수", meaning: "가수", level: "준6", chars: ["H0151", "H0079"] },

  // ===== 6급 단어 =====
  { id: "W0106", hanja: "價格", reading: "가격", meaning: "가격", level: "6", chars: ["H0226", "H0230"] },
  { id: "W0107", hanja: "强力", reading: "강력", meaning: "강력", level: "6", chars: ["H0228", "H0051"] },
  { id: "W0108", hanja: "意見", reading: "의견", meaning: "의견", level: "6", chars: ["H0231", "H0159"] },
  { id: "W0109", hanja: "義務", reading: "의무", meaning: "의무", level: "6", chars: ["H0232", "H0192"] },
  { id: "W0110", hanja: "會議", reading: "회의", meaning: "회의", level: "6", chars: ["H0209", "H0233"] },
  { id: "W0111", hanja: "根本", reading: "근본", meaning: "근본", level: "6", chars: ["H0234", "H0204"] },
  { id: "W0112", hanja: "期間", reading: "기간", meaning: "기간", level: "6", chars: ["H0235", "H0153"] },
  { id: "W0113", hanja: "自然", reading: "자연", meaning: "자연", level: "6", chars: ["H0077", "H0237"] },
  { id: "W0114", hanja: "約束", reading: "약속", meaning: "약속", level: "6", chars: ["H0238", "H0080"] },
  { id: "W0115", hanja: "太陽", reading: "태양", meaning: "태양", level: "6", chars: ["H0276", "H0239"] },
  { id: "W0116", hanja: "溫度", reading: "온도", meaning: "온도", level: "6", chars: ["H0243", "H0180"] },
  { id: "W0117", hanja: "完全", reading: "완전", meaning: "완전", level: "6", chars: ["H0244", "H0222"] },
  { id: "W0118", hanja: "銀行", reading: "은행", meaning: "은행", level: "6", chars: ["H0245", "H0207"] },
  { id: "W0119", hanja: "位置", reading: "위치", meaning: "위치", level: "6", chars: ["H0247", "H0269"] },
  { id: "W0120", hanja: "原因", reading: "원인", meaning: "원인", level: "6", chars: ["H0142", "H0249"] },
  { id: "W0121", hanja: "作品", reading: "작품", meaning: "작품", level: "6", chars: ["H0251", "H0281"] },
  { id: "W0122", hanja: "戰爭", reading: "전쟁", meaning: "전쟁", level: "6", chars: ["H0255", "H0255"] },
  { id: "W0123", hanja: "政治", reading: "정치", meaning: "정치", level: "6", chars: ["H0258", "H0274"] },
  { id: "W0124", hanja: "祖國", reading: "조국", meaning: "조국", level: "6", chars: ["H0261", "H0063"] },
  { id: "W0125", hanja: "民族", reading: "민족", meaning: "민족", level: "6", chars: ["H0064", "H0262"] },
  { id: "W0126", hanja: "進步", reading: "진보", meaning: "진보", level: "6", chars: ["H0266", "H0125"] },
  { id: "W0127", hanja: "最初", reading: "최초", meaning: "최초", level: "6", chars: ["H0271", "H0270"] },
  { id: "W0128", hanja: "親切", reading: "친절", meaning: "친절", level: "6", chars: ["H0275", "H0254"] },
  { id: "W0129", hanja: "特別", reading: "특별", meaning: "특별", level: "6", chars: ["H0277", "H0123"] },
  { id: "W0130", hanja: "通信", reading: "통신", meaning: "통신", level: "6", chars: ["H0278", "H0135"] },
  { id: "W0131", hanja: "必要", reading: "필요", meaning: "필요", level: "6", chars: ["H0282", "H0139"] },
  { id: "W0132", hanja: "解決", reading: "해결", meaning: "해결", level: "6", chars: ["H0286", "H0160"] },
  { id: "W0133", hanja: "效果", reading: "효과", meaning: "효과", level: "6", chars: ["H0291", "H0107"] },
  { id: "W0134", hanja: "訓練", reading: "훈련", meaning: "훈련", level: "6", chars: ["H0292", "H0292"] },
  { id: "W0135", hanja: "精神", reading: "정신", meaning: "정신", level: "6", chars: ["H0257", "H0085"] },
  { id: "W0136", hanja: "終了", reading: "종료", meaning: "종료", level: "6", chars: ["H0264", "H0264"] },
  { id: "W0137", hanja: "存在", reading: "존재", meaning: "존재", level: "6", chars: ["H0263", "H0252"] },
  { id: "W0138", hanja: "退場", reading: "퇴장", meaning: "퇴장", level: "6", chars: ["H0279", "H0069"] },
  { id: "W0139", hanja: "表現", reading: "표현", meaning: "표현", level: "6", chars: ["H0280", "H0223"] },
  { id: "W0140", hanja: "港口", reading: "항구", meaning: "항구", level: "6", chars: ["H0285", "H0081"] },
];
